# Generated by Django 3.2.7 on 2021-12-14 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/images')),
                ('name', models.CharField(max_length=60, verbose_name='Ad')),
                ('front_description', models.CharField(max_length=100, verbose_name='On melumat')),
                ('back_description', models.CharField(max_length=500, verbose_name='Arxa melumat')),
                ('number', models.CharField(max_length=20, verbose_name='Telefon nomresi')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('number', models.CharField(max_length=15, verbose_name='Number')),
                ('email', models.EmailField(max_length=40, verbose_name='E-mail')),
                ('message', models.CharField(max_length=256, verbose_name='Mesagge')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/images')),
                ('date', models.CharField(max_length=60, verbose_name='Name')),
                ('description', models.CharField(max_length=100, verbose_name='Name')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('menager', models.CharField(max_length=60, verbose_name='Name')),
                ('menager_job', models.CharField(max_length=60, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='University_left',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Ad')),
                ('date', models.CharField(max_length=60, verbose_name='Tarix')),
                ('description', models.CharField(max_length=1200, verbose_name='Melumat')),
                ('image', models.ImageField(upload_to='media/images')),
            ],
        ),
        migrations.CreateModel(
            name='University_right',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Ad')),
                ('date', models.CharField(max_length=60, verbose_name='Tarix')),
                ('description', models.CharField(max_length=1200, verbose_name='Melumat')),
                ('image', models.ImageField(upload_to='media/images')),
            ],
        ),
    ]
