# Generated by Django 3.2.7 on 2021-12-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.CharField(max_length=60, verbose_name='Tarix'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Melumat'),
        ),
        migrations.AlterField(
            model_name='project',
            name='menager',
            field=models.CharField(max_length=60, verbose_name='Menecer'),
        ),
        migrations.AlterField(
            model_name='project',
            name='menager_job',
            field=models.CharField(max_length=60, verbose_name='Menecerin isi'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Ad'),
        ),
    ]
